-- ============================================================
-- shop-billing-db — Seed Data
-- Passwords below are bcrypt hashes of "Test@1234"
-- Replace with real hashes generated by your auth layer before production
-- ============================================================

-- 1. Shop
INSERT INTO shops (id, name, owner_email, logo_url, created_at) VALUES
  ('shop-001', 'Demo Retail Store', 'owner@demostore.com', NULL, datetime('now'));

-- 2. Users
-- admin  password: Test@1234  (bcrypt hash)
INSERT INTO users (id, shop_id, name, username, password_hash, role, created_at) VALUES
  ('user-admin-001', 'shop-001', 'Store Owner', 'admin',
   '$2a$10$H4kAQq8oQe/zCmagt037RuWRXh65p55zCzinrMvHpNL9aVrpYenlC',
   'admin', datetime('now'));

-- salesman  password: Test@1234  (bcrypt hash)
INSERT INTO users (id, shop_id, name, username, password_hash, role, created_at) VALUES
  ('user-sales-001', 'shop-001', 'Ravi Kumar', 'ravi',
   '$2a$10$H4kAQq8oQe/zCmagt037RuWRXh65p55zCzinrMvHpNL9aVrpYenlC',
   'salesman', datetime('now'));

-- 3. Products (3 samples with barcode + low_stock_threshold)
INSERT INTO products (id, shop_id, name, barcode, price, stock_qty, low_stock_threshold, updated_at) VALUES
  ('prod-001', 'shop-001', 'Lays Classic Chips 26g', '8901015144009', 20.00, 50, 10, datetime('now')),
  ('prod-002', 'shop-001', 'Parle-G Biscuit 100g',  '8901719110116', 10.00, 80, 15, datetime('now')),
  ('prod-003', 'shop-001', 'Coca-Cola 250ml Can',   '5449000000996', 40.00, 30,  5, datetime('now'));

-- 4. Customer
INSERT INTO customers (id, shop_id, name, phone, credit_balance, created_at) VALUES
  ('cust-001', 'shop-001', 'Suresh Babu', '9876543210', 0.00, datetime('now'));

-- 5. Vendor
INSERT INTO vendors (id, shop_id, name, phone, created_at) VALUES
  ('vendor-001', 'shop-001', 'City Wholesale Distributors', '9988776655', datetime('now'));
